cabal-version:      3.0
name:               JustArkoLang
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Saiyam Chettri
maintainer:         saiyum303@gmail.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  MyLib,
                      Lisp
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.17.2.1,
                      mtl >= 2.2.2,
                      parsec
    hs-source-dirs:   src
    default-language: GHC2021

executable JustArkoLang
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.17.2.1,
        JustArkoLang

    hs-source-dirs:   app
    default-language: GHC2021

test-suite JustArkoLang-test
    import:           warnings
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.17.2.1,
        JustArkoLang
